version: '3'

services:
  spring-boot:
    build:
      context: ./backend
    image: spring-boot/lts
    container_name: spring-boot
    ports:
      - "${SPRING_BOOT_HOST_PORT}:${SPRING_BOOT_APP_PORT}"
